name: Wettertext generieren

on:
  workflow_dispatch:

jobs:
  generate-wettertext:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Repo klonen
        uses: actions/checkout@v3

      - name: Node.js einrichten
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Abhängigkeiten installieren
        run: npm install node-fetch@2

      - name: Wettertext generieren
        run: node scripts/generateChatGPTText.js

      - name: Änderungen committen und pushen
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/chatgpt_live.html
          git commit -m "Update: Neuer Live-Wettertext (automatisch generiert)" || echo "Nichts zu committen"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
